# Generated by Django 2.2.10 on 2020-02-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0002_auto_20200225_0854"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="card_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="expire_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
